### ISSUE TITLE
feature request: add width option for visualizer

### ISSUE THREAD

**Issue by junguler** [mfcc64/mpv-scripts#10]
hi, i had a lot of issues setting mpv window size when playing audio but your amazing script seems to have fixed it for me while looking cool doing it, the only issue i have left is the window is too wide and i like to have the option to set width too if it's possible.

**Comment by mfcc64** [comment]
There has been 'quality' option.

**Comment by junguler** [comment]
i have already set quality to "verylow " which helps with height but width is still really wide and i like to have the option to reduce it's size if possible.

**Comment by junguler** [comment]
ok you were right, there is an option for this already on the line 143, sorry, my bad.
