### ISSUE TITLE
[Feature Request] Off Visualizer should show black screen

### ISSUE THREAD

**Issue by barraIhsan** [mfcc64/mpv-scripts#13]
There are 4 conditions:
1. Set the `name` to `off`, Run the audio from GUI (explorer/finder). It will show up as a black screen ✅ 
2. Set the `name` to `off`, Run the audio from the terminal. It doesn't show up anything ❎ (Although it's normal (without this scripts) I think you should still show up the window. Or maybe add the option if you still want to show up the window?)
3. Set the `name` to not `off`. Run the audio from GUI (explorer/finder). Cycle it with `c`. The visualizer freeze on the previous state (`showwaves`) ❎ 
4. Set the `name` to not `off`. Run the audio from the terminal. Cycle it with `c`. The MPV window disappears, but still, play the video, you still can cycle it with `c` in the terminal ❎ (Although it's normal (without this scripts) I think you should still show up the window. Or maybe add the option if you still want to show up the window?)

I suggest it will show up normally (black screen), just like the number 1

**Comment by mfcc64** [comment]
Check #14
