### ISSUE TITLE
Visualizer not showing with mpv --no-video command

### ISSUE THREAD

**Issue by akash-258** [mfcc64/mpv-scripts#17]
The visualizer is working fine for audio files but when playing a video file with `mpv --player-operation-mode=pseudo-gui --no-video filename.mp4`, the visualizer is not showing up.
I use this functionality to listen to youtube videos as audio with "open with" firefox extention and this command `mpv --player-operation-mode=pseudo-gui --no-video --fs=no`.

**Comment by mfcc64** [comment]
use `--script-opts=visualizer-mode=force`

Or maybe you want to use [YouTube Musical Spectrum](https://github.com/mfcc64/youtube-musical-spectrum)

**Comment by akash-258** [comment]
>use --script-opts=visualizer-mode=force

Using this forces visualizer in videos also, which is not desirable.

>Or maybe you want to use [YouTube Musical Spectrum](https://github.com/mfcc64/youtube-musical-spectrum)

I dont want visualizer in youtube videos in browser, I wanted to use it in mpv

It's ok if the functionality is not supported in the way I want it

**Comment by akash-258** [comment]
Thank you so much, working just as expected.
