### ISSUE TITLE
feature request: visualizer keybind

### ISSUE THREAD

**Issue by bitingsock** [mfcc64/mpv-scripts#2]
Great work!
Is it possible to have a keybind to cycle through your different visualizations?

**Comment by mfcc64** [comment]
Does abdd15c7efd8ebb8cb8d36c0d2591eaeb3cb839d work?

**Comment by bitingsock** [comment]
Yes, but I have to reload it for it to take effect. I made a workaround for now.
`mp.command("write_watch_later_config")
	mp.commandv("loadfile", mp.get_property("path"), "replace")`
at the end of the cycle function

**Comment by bitingsock** [comment]
Also, when cycling around to "no" it leaves the last image of showwaves up and doesn't clear it.

**Comment by mfcc64** [comment]
> Yes, but I have to reload it for it to take effect. It seems that last visualizer_hook() call at the end of the cycle function isn't working? I made a workaround for now.

Probably, https://github.com/mpv-player/mpv/commit/f1d161d55f458cf47e63d1ab9ddf08859019dd8a is required.

>`mp.command("write_watch_later_config")`
`mp.commandv("loadfile", mp.get_property("path"), "replace")`
at the end of the cycle function.
I am on windows btw

Of course this restarts playback and clears playlist.

>Also, when cycling around to "no" it leaves the last image of showwaves up and doesn't clear it.

I have no idea how to fix this.

**Comment by bitingsock** [comment]
https://github.com/mpv-player/mpv/commit/f1d161d55f458cf47e63d1ab9ddf08859019dd8a
is probably what i need my build is kinda old.
Anyway, I'll consider this done. Thanks for the feature!
