### ISSUE TITLE
Can't play music files in terminal without opening mpv with gui

### ISSUE THREAD

**Issue by akash-258** [mfcc64/mpv-scripts#21]
Without the script when playing music files from terminal, mpv does not open a window and played music in terminal only.
With script, when playing the music file from terminal, mpv window is launched with the visualizer.

Can the script be configured to only show visualizer when a file is played by right-clicking or played with mpv command `--player-operation-mode=pseudo-gui`  and does not trigger to open a mpv window when playing music files from terminal?

**Comment by christoph-heinrich** [comment]
The default behavior of mpv is that when opened with `force-window=no` and you cycle your video track to `no`, the window disappears and you're left only with the terminal.
Should with the script in that case the window also disappear, or keep the window open and start visualizer?

**Comment by akash-258** [comment]
This issue is still present in the current version of the script. @christoph-heinrich @mfcc64
