### ISSUE TITLE
Error with visualizer.lua

### ISSUE THREAD

**Issue by kesdoputr** [mfcc64/mpv-scripts#34]
Hello, i am using mpv with visualizer.lua for years and it works well.
But in this month i found i can't play mp3 files when it has no album art embed.
I will get the error below
![Clip279](https://github.com/mfcc64/mpv-scripts/assets/16981364/96d9f0bf-d56a-44f8-b8ab-fd02ea720adf)

I am using windows 10 x64 bit with the build 
https://sourceforge.net/projects/mpv-player-windows/files/64bit/
The error occur after the build **mpv-x86_64-20240211-git-f5c4f0b.7z**

When i remove visualizer.lua mpv can play these mp3 normal.
Below is the test mp3 file
https://xgf.nu/d0SS3

Thanks for your reading.

**Comment by mfcc64** [comment]
Fixed

Thank's
