### ISSUE TITLE
latest git mpv breaks showspectrum and showcqtbar colorspace

### ISSUE THREAD

**Issue by gamernoob24** [mfcc64/mpv-scripts#39]
only specific to gpu-next from this commit

https://github.com/mpv-player/mpv/commit/ef6052c01e323cece4ace135a1724fd09f86c86d

**Comment by mrfragger** [comment]
yep sure does...great catch.  Adds an annoying greenish background
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/c83ff10c-bcad-4191-bb08-eb8f4315b20f">

**Comment by gamernoob24** [comment]
oh right they did

![image](https://github.com/user-attachments/assets/9df903a5-be92-49c9-972e-533def3129ca)
