### ISSUE TITLE
Visualizer glitch

### ISSUE THREAD

**Issue by Keith94** [mfcc64/mpv-scripts#4]
I don't think it's supposed to look like this, right?

![01 alternative reality_00_00_49 338](https://user-images.githubusercontent.com/5490615/32997156-f5b0adbe-cd40-11e7-919e-5cd6fc121be3.png)

**Comment by mfcc64** [comment]
What do you mean? What's wrong?

**Comment by Keith94** [comment]
I mean, from my screenshot the visualizer shows weird characters in the middle and the pattern is repeating... I thought maybe it's a bug? Or is that the intended look?

**Comment by mfcc64** [comment]
It is the intended look. I changed it at 837724990411e10d128c62fee872b2231093932c. It just follows my taste. If you dislike it, just comment out axisfile option (and the axis become red-blue repeated musical notes), or you may set it to your own axis image.

Currently, I have no plan to make it configurable. So, you should set it manually at filtergraph definition.

Thank's.

**Comment by Keith94** [comment]
Interesting, thanks.
