### ISSUE TITLE
mpv crash with visualizer.lua?

### ISSUE THREAD

**Issue by bturkus** [mfcc64/mpv-scripts#5]
Hi,

First, I just wanted to say: this the coolest! I'd love to get it working, but unfortunately, every time I drop in an audio file (wav or flac), mpv crashes. I have been able to get firequalizer15.lua working, so I'm not sure exactly where the problem lies. It could be my general cluelessness when it comes to mpv and lua, but any help at all would be really appreciated.

I'm on mpv 0.27.0 for macOS, and I've been placing visualizer.lua in a scripts directory within mpv's .config 

Thanks!
Ben

**Comment by mfcc64** [comment]
Can you provide log file?

**Comment by bturkus** [comment]
Ah, so sorry about that. Log here: https://pastebin.com/uX8KVurL
Thanks again!

**Comment by mfcc64** [comment]
> [   0.049][e][ffmpeg] Parsed_showcqt_4: Option 'attack' not found

This is similar to #1. You need at least ffmpeg 3.4 or ffmpeg master. Or alternatively, you can comment out this option.

Thank's.

**Comment by bturkus** [comment]
Thanks for the help, and for the quick response.
