### ISSUE TITLE
Feature request / question

### ISSUE THREAD

**Issue by PinusCembra** [mfcc64/mpv-scripts#7]
Is there any way to turn off the visualization of the bar and the keys when using `showcqt` and `showcqtbar` for the visualizer.lua?
I tried to mess around a bit but couldn't manage do it myself.

**Comment by mfcc64** [comment]
Maybe you can try editing showcqt parameter.
To turn off the bar, try bar_h = 0.
To remove keys, try axis = 0.

Thank's.

**Comment by PinusCembra** [comment]
Thanks a lot. I completely overlooked that
