### ISSUE TITLE
Key for toggling the visualizer

### ISSUE THREAD

**Issue by jagrg** [mfcc64/mpv-scripts#8]
The visualizer looks nice. Thanks for your work. Is there a way of opening the visualizer on demand by pressing a key?

Also, I'm getting a warning when the script loads:
```
[ffmpeg] Parsed_showcqt_4: fractional step
```
Do you know what this is?

**Comment by mfcc64** [comment]
Add script-opts=visualizer-name=off,visualizer-mode=force or just modify the script directly. Press 'c' to cycle (modify the script if you want to bind different key).

**Comment by jagrg** [comment]
Yes, that works. Thanks!

**Comment by barraIhsan** [comment]
Can we toggle it like
`C cycle-values script-opts visualizer-name "off" "showcqtbar"`
